Schema Inheritance Error
>> TypeError: Cannot read property '0' of undefined.
https://github.com/briankircho/mongoose-schema-extend/issues/56

This fix is works for me.  Check my edits please. Maybe you could find a better solution and my edits could help you, because I'm not sure that my solution is the best one.